### ISSUE TITLE
Actions need to be updated to v3 to avoid deprecation

### ISSUE THREAD

**Issue by nikParasyr** [EmilienM/devstack-action#10]
Workflows have the following warning:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout

Need to update to `v3` to use Node.js 16

**Comment by EmilienM** [comment]
@nikParasyr released: https://github.com/EmilienM/devstack-action/releases/tag/v0.9
