### ISSUE TITLE
Error/Doubt regarding using devstack action to test Ansible roles

### ISSUE THREAD

**Issue by jacobdotcosta** [EmilienM/devstack-action#14]
Hi.

I'm trying to implement a PR check on my ansible collection project and wanted to start by checking a role that creates VMs on OpenStack. I've created the github action ([this one](https://github.com/jacobdotcosta/k8s-infra/blob/ansible_collection/.github/workflows/pr.yml)) but my roles fail because Ansible is not able to connect to the auth service. 

On the `devstack-action` log I see a message that seems to indicate that the auth service is not available ([line 17810](https://github.com/jacobdotcosta/k8s-infra/actions/runs/5382895295/jobs/9768945731#step:3:17810)).

```
+ home/runner/work/k8s-infra/k8s-infra/devstack/tools/create_userrc.sh:main:241 :   read project_id project_name desc enabled
Failed to discover available identity versions when contacting http://localhost:5000/v3/. Attempting to parse version from URL.
Unable to establish connection to http://localhost:5000/v3/auth/tokens: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /v3/auth/tokens (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb37dee6d10>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

On my Ansible log I have a similar message.

```
  TASK [openstack_vm : Get VM information] ***************************************
  fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Failed to discover available identity versions when contacting http://localhost:5000/v3/. Attempting to parse version from URL.
```

The services I'm enabling are the following: `enabled_services: 's-account,s-container,s-object,s-proxy'`

Do you know if I should be able to use this service? Would I have to enable a specific service for this? 

I'm using version `EmilienM/devstack-action@v0.11`.

Thank you.

**Comment by EmilienM** [comment]
I see in https://github.com/jacobdotcosta/k8s-infra/actions/runs/5387886485/jobs/9779814535 that devstack finished correctly:

```
 This is your host IP address: 10.1.0.45
This is your host IPv6 address: ::1
Keystone is serving at http://10.1.0.45/identity/
The default users are: admin and demo
The password: secret
```

What did I miss?

**Comment by jacobdotcosta** [comment]
I was using the address obtained from `OS_AUTH_URL` (`http://localhost:5000/v3/`) as authentication URL.
Using the one obtained from the `KEYSTONE_SERVICE_URI` does the trick. 

Thank you.
