### ISSUE TITLE
unmaintained openstack releases

### ISSUE THREAD

**Issue by k0ka** [EmilienM/devstack-action#22]
Hello,

I saw you dropped support of unmaintained releases - https://github.com/EmilienM/devstack-action/pull/21
But while it is not recommended to install these releases, a lot of people might have them installed internally and I have to check my library against them for backward compatibility. Are you planning to support them or would you accept PR with support for them?

**Comment by EmilienM** [comment]
You can still install whatever version you like. We just removed the CI jobs to avoid testing the unmaintained & unsupported releases in OpenStack. But you can still use this Github Action to deploy any OpenStack version that you like, at your own risk.

**Comment by k0ka** [comment]
Well, not really. Trying to install `unstable/yoga` release shows error with git as it tries to fetch `stable/yoga` branch which doesn't exist anymore - https://github.com/php-opencloud/openstack/actions/runs/8550781380/job/23428430991?pr=408

I'll try to override `TARGET_BRANCH` as you did before https://github.com/EmilienM/devstack-action/commit/e82a9cbead099cba72f99537e82a360c3e319c69

**Comment by k0ka** [comment]
Yes, adding `TARGET_BRANCH=unstable/yoga` to `conf_overrides` installs it properly. But I guess it's better to at least document or better add it automatically.
