### ISSUE TITLE
'Workaround for docker.io' removes docker in Github Action

### ISSUE THREAD

**Issue by Lirt** [EmilienM/devstack-action#8]
Hello,

I'm trying to use `devstack-action` similar as it is used in gophercloud to run integration tests in [velero plugin for openstack](https://github.com/Lirt/velero-plugin-for-openstack) repository that I maintain.

The part of code with [workaround for docker.io](https://github.com/EmilienM/devstack-action/blob/aa67c93616800436a30872a32763b5f1ac23bc69/action.yaml#L31-L34) actually removes `docker*` packages from the VM (Tested with ubuntu-20.04).

```yaml
    - name: Workaround for docker.io
      run: |
        sudo apt-get install -y runc || true
      shell: bash
```

This make me unable to perform test in which I need docker to create `kind` cluster and deploy devstack in the same job.

Solution for me would be to insert condition (input variable probably) to skip this workaround part of the code. I tested without it and for my simple use-case (swift+cinder+keystone+mysql) devstack deploys correctly. I don't know what exactly is the workaround for, so maybe also adding a comment there would help others to understand. 

If you agree with my suggestion I can open the PR for the new version.

Thank you for your help.

**Comment by EmilienM** [comment]
Go for it :)

**Comment by EmilienM** [comment]
@Lirt done and released! thanks :-)

**Comment by Lirt** [comment]
Thank you very much
